from django.urls import path
from .views import (
    home_view, about_view, dashboard_view, calendar_view, add_event, view_event, todo_list, add_todo, mark_completed, delete_todo, edit_attendance_view, update_attendance,
    class_cleanliness_view, edit_class_cleanliness, delete_class_cleanliness, club_report_view, edit_club_report, delete_club_report, log_book_view, edit_log_book, delete_log_book,
    reading_log_view, edit_reading_log, delete_reading_log, staff_attendance_view, edit_staff_attendance, delete_staff_attendance, supw_report_view, edit_supw_report, delete_supw_report,
    teachers_substitution_view, edit_teachers_substitution, delete_teachers_substitution, teachers_timetable_view, edit_teachers_timetable, delete_teachers_timetable,
    tod_report_view, edit_tod_report, delete_tod_report, organization_chart_view, edit_organization_chart, delete_organization_chart, professional_development_view,
    edit_professional_development, delete_professional_development, plc_report_view, edit_plc_report, delete_plc_report,pie_chart_view
)

urlpatterns = [
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('calendar/', calendar_view, name='calendar'),
    path('add_event/', add_event, name='add_event'),
    path('view_event/<int:event_id>/', view_event, name='view_event'),
    path('todos/', todo_list, name='todo_list'),
    path('add_todo/', add_todo, name='add_todo'),
    path('mark_completed/<int:todo_id>/', mark_completed, name='mark_completed'),
    path('delete_todo/<int:todo_id>/', delete_todo, name='delete_todo'),
    path('edit_attendance/', edit_attendance_view, name='edit_attendance'),
    path('update_attendance/', update_attendance, name='update_attendance'),
    path('class_cleanliness/', class_cleanliness_view, name='class_cleanliness'),
    path('class_cleanliness/edit/<int:pk>/', edit_class_cleanliness, name='edit_class_cleanliness'),
    path('class_cleanliness/delete/<int:pk>/', delete_class_cleanliness, name='delete_class_cleanliness'),
    path('club_report/', club_report_view, name='club_report'),
    path('club_report/edit/<int:pk>/', edit_club_report, name='edit_club_report'),
    path('club_report/delete/<int:pk>/', delete_club_report, name='delete_club_report'),
    path('log_book/', log_book_view, name='log_book'),
    path('log_book/edit/<int:pk>/', edit_log_book, name='edit_log_book'),
    path('log_book/delete/<int:pk>/', delete_log_book, name='delete_log_book'),
    path('reading_log/', reading_log_view, name='reading_log'),
    path('reading_log/edit/<int:pk>/', edit_reading_log, name='edit_reading_log'),
    path('reading_log/delete/<int:pk>/', delete_reading_log, name='delete_reading_log'),
    path('staff_attendance/', staff_attendance_view, name='staff_attendance'),
    path('staff_attendance/edit/<int:pk>/', edit_staff_attendance, name='edit_staff_attendance'),
    path('staff_attendance/delete/<int:pk>/', delete_staff_attendance, name='delete_staff_attendance'),
    path('supw_report/', supw_report_view, name='supw_report'),
    path('supw_report/edit/<int:pk>/', edit_supw_report, name='edit_supw_report'),
    path('supw_report/delete/<int:pk>/', delete_supw_report, name='delete_supw_report'),
    path('teachers_substitution/', teachers_substitution_view, name='teachers_substitution'),
    path('teachers_substitution/edit/<int:pk>/', edit_teachers_substitution, name='edit_teachers_substitution'),
    path('teachers_substitution/delete/<int:pk>/', delete_teachers_substitution, name='delete_teachers_substitution'),
    path('teachers_timetable/', teachers_timetable_view, name='teachers_timetable'),
    path('teachers_timetable/edit/<int:pk>/', edit_teachers_timetable, name='edit_teachers_timetable'),
    path('teachers_timetable/delete/<int:pk>/', delete_teachers_timetable, name='delete_teachers_timetable'),
    path('tod_report/', tod_report_view, name='tod_report'),
    path('tod_report/edit/<int:pk>/', edit_tod_report, name='edit_tod_report'),
    path('tod_report/delete/<int:pk>/', delete_tod_report, name='delete_tod_report'),
    path('organization_chart/', organization_chart_view, name='organization_chart'),
    path('organization_chart/edit/<int:pk>/', edit_organization_chart, name='edit_organization_chart'),
    path('organization_chart/delete/<int:pk>/', delete_organization_chart, name='delete_organization_chart'),
    path('professional_development/', professional_development_view, name='professional_development'),
    path('professional_development/edit/<int:pk>/', edit_professional_development, name='edit_professional_development'),
    path('professional_development/delete/<int:pk>/', delete_professional_development, name='delete_professional_development'),
    path('plc_report/', plc_report_view, name='plc_report'),
    path('plc_report/edit/<int:pk>/', edit_plc_report, name='edit_plc_report'),
    path('plc_report/delete/<int:pk>/', delete_plc_report, name='delete_plc_report'),
    path('pie_chart/', pie_chart_view, name='pie_chart'),
]
