# Generated by Django 5.0.7 on 2024-07-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCleanliness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('class_name', models.CharField(max_length=100)),
                ('cleanliness_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClubReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('club_name', models.CharField(max_length=100)),
                ('report', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LogBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('student_name', models.CharField(max_length=100)),
                ('book_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('teacher_name', models.CharField(max_length=100)),
                ('present', models.BooleanField(default=True)),
            ],
        ),
    ]
