# Generated by Django 5.0.7 on 2024-07-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_classcleanliness_clubreport_logbook_readinglog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chart', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PLCReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('report', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity_name', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SUPWReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity_name', models.CharField(max_length=100)),
                ('report', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeachersSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('teacher_name', models.CharField(max_length=100)),
                ('substitute_teacher', models.CharField(max_length=100)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeachersTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('teacher_name', models.CharField(max_length=100)),
                ('timetable', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TODReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('report_details', models.TextField()),
            ],
        ),
    ]
